### ISSUE TITLE
Milestone v1

### ISSUE THREAD

**Issue by saadshahd** [eventtus/react-redux-thunk-rest-api#2]
- [x] Pick short  name #3 
- [ ] Add [flow](https://flow.org)
- [ ] Add documentation
- [ ] Expose the value behind creating this
- [ ] Organize the public API as the taken feedback from beta devs reported in 
- [ ] Add contributors whole of fame
